---

- name: Generate temporary rules script
  template:
    src: iptables-rules.sh.j2
    dest: "{{ iptables_rules_path }}"
    backup: no
    mode: '0755'
    owner: root
    group: root

- name: Apply temporary rules
  command: "{{ iptables_rules_path }}"

- name: Save temporary rules to permanent location
  command: "/usr/libexec/iptables/iptables.init save"

- name: Flush temporary rules
  command: "/usr/sbin/iptables -F"

- name: Remove temporary rules script
  file:
    path: /tmp/iptables-rules.sh
    state: absent

- name: Enable service and load rules from permanent location
  service:
    name: iptables
    enabled: yes
    state: restarted
